---
title: "A Project on Facebook Page Performance of a Cosmetic Brand"
author: "Rajiv"
date: "5 April 2017"
output:
  html_document: default
  word_document: default
---

```{r Importing_Dataset, echo=TRUE, message=FALSE, warning=FALSE}
rm(list=ls())
library(RCurl)
facebook_page <- read.table(text = getURL("https://raw.githubusercontent.com/Rajiv2806/SA-2-Mini-Project-1-Facebook-Page-Sales/master/Facebook.csv"),header = T,sep = ",")
```

```{r Renaming_Fields, echo=TRUE, message=FALSE, warning=FALSE}
names(facebook_page) <- c("Page_Likes","Type","Category","Month","Weekday","Hour","Paid"
                          ,"Reach","Impressions","Engaged","Consumers","Consumptions"
                          ,"Impressions_Liked","Reach_Liked","Engaged_Liked"
                          ,"Comment","Like","Share","Interactions")
facebook_page <- facebook_page[,c(19,2,3,7,4,5,6,8,14,9,13,10,15,11,12,16,17,18,1)]
```

```{r Calculated_Fields, message=FALSE, warning=FALSE}
facebook_page$Impressions_in_100 <- facebook_page$Impressions/100
facebook_page$ImpressionsRate_Liked <- (facebook_page$Impressions_Liked/facebook_page$Page_Likes)*100
facebook_page$ReachRate <- (facebook_page$Reach/facebook_page$Impressions)*100
facebook_page$ReachRate_Liked <- (facebook_page$Reach_Liked/facebook_page$Impressions_Liked)*100
facebook_page$EngagedRate <- (facebook_page$Engaged/facebook_page$Reach)*100
facebook_page$EngagedRate_Liked <- (facebook_page$Engaged_Liked/facebook_page$Reach_Liked)*100
facebook_page$ConsumerRate <- (facebook_page$Consumers/facebook_page$Engaged)*100
facebook_page$consumptionRate <- (facebook_page$Consumptions/facebook_page$Reach) * 100
facebook_page <- facebook_page[,c(27,2,3,4,20,21,22,23,24,25,26,1)]
```

```{r Creating_Factor_Var, message=FALSE, warning=FALSE}
facebook_page$Paid[facebook_page$Paid == 1] = "Yes"
facebook_page$Paid[facebook_page$Paid == 0] = "No"
facebook_page$Paid <- as.factor(facebook_page$Paid)

facebook_page$Category[facebook_page$Category == 1] = "Action"
facebook_page$Category[facebook_page$Category == 2] = "Product"
facebook_page$Category[facebook_page$Category == 3] = "Inspiration"
facebook_page$Category <- as.factor(facebook_page$Category)
```

```{r Examining_Data, message=FALSE, warning=FALSE}
class(facebook_page)
dim(facebook_page)
sapply(facebook_page,class)
```

```{r Maiisigdata_Handling, message=FALSE, warning=FALSE}
sum(is.na(facebook_page))
colSums(is.na(facebook_page))
table(facebook_page$Paid)
facebook_page$Paid[is.na(facebook_page$Paid)] = "No"
sum(is.na(facebook_page))
```

```{r summary_of_Dataset, message=FALSE, warning=FALSE}
summary(facebook_page)
```

```{r Univariate_Analysis, message=FALSE, warning=FALSE}
par(mfrow=c(3,2))
boxplot(facebook_page$Impressions_in_100,main = "Total Impressions in 100's")
boxplot(facebook_page$ImpressionsRate_Liked,main = "Impression Rate Who Liked or Page")
boxplot(facebook_page$ReachRate,main = "Reach Rate")
boxplot(facebook_page$ReachRate_Liked,main = "Reach Rate Who Liked or Page")
boxplot(facebook_page$EngagedRate,main = "Engaged User Rate")
boxplot(facebook_page$EngagedRate_Liked,main = "Engaged Users who Liked Our Page")
par(mfrow=c(1,3))
boxplot(facebook_page$Interactions,main = "Total Interactions")
boxplot(facebook_page$ConsumerRate, main = "Consumer Rate")
boxplot(facebook_page$consumptionRate,main = "Consumption Rate")
```

```{r Bivariate_Analysis, message=FALSE, warning=FALSE}
library(PerformanceAnalytics)
chart.Correlation(facebook_page[,sapply(facebook_page,is.numeric)])
```

```{r Data_Partitioning, message=FALSE, warning=FALSE}
rownumbers <- sample(1:nrow(facebook_page),size = 0.8*nrow(facebook_page))
facebook_train <- facebook_page[rownumbers,]
facebook_Validation <- facebook_page[-rownumbers,]
```

```{r Model0, message=FALSE, warning=FALSE}
Model0 <- lm(consumptionRate~
                 +Type + Category + Paid 
                 +Impressions_in_100 + ImpressionsRate_Liked 
                 +ReachRate + ReachRate_Liked
                 +EngagedRate + EngagedRate_Liked
                 +ConsumerRate + Interactions
                 ,data = facebook_train)
summary(Model0)
library(car)
qqPlot(Model0)
residualPlots(Model0)
```

```{r Transformations_Model0, message=FALSE, warning=FALSE}
consumptionRate_Log <- log(facebook_train$consumptionRate)
Impressions_in_100_Log <- log(facebook_train$Impressions_in_100)
ImpressionsRate_Liked_Log <- log(facebook_train$ImpressionsRate_Liked)
ReachRate_Log <- log(facebook_train$ReachRate)
ReachRate_Liked_Log <- log(max(facebook_train$ReachRate_Liked)+1-facebook_train$ReachRate_Liked)
EngagedRate_Log <- log(facebook_train$EngagedRate)
EngagedRate_Liked_Log <- log(facebook_train$EngagedRate_Liked)
ConsumerRate_Log <- log(max(facebook_train$ConsumerRate)+1- facebook_train$ConsumerRate)
facebook_train <- cbind(facebook_train,consumptionRate_Log,Impressions_in_100_Log,ImpressionsRate_Liked_Log,ReachRate_Log,ReachRate_Liked_Log,EngagedRate_Log,EngagedRate_Liked_Log,ConsumerRate_Log)
rm(consumptionRate_Log,Impressions_in_100_Log,ImpressionsRate_Liked_Log,ReachRate_Log,ReachRate_Liked_Log,EngagedRate_Log,EngagedRate_Liked_Log,ConsumerRate_Log)
```

```{r Model1, message=FALSE, warning=FALSE}
Model1 <- lm(consumptionRate_Log~
                 +Type+Category+Paid 
                 +Impressions_in_100_Log + ImpressionsRate_Liked_Log 
                 +ReachRate_Log + ReachRate_Liked_Log
                 +EngagedRate_Log + EngagedRate_Liked_Log
                 +ConsumerRate_Log
                 +Interactions
                 ,data = facebook_train)

summary(Model1)
qqPlot(Model1,id.n = 10)
residualPlot(Model1)
residualPlots(Model1)
influenceIndexPlot(Model1,id.n=5)
```

```{r Transformations_Model1, message=FALSE, warning=FALSE}
Impressions_in_100_Log_Sq <- facebook_train$Impressions_in_100_Log^2
ImpressionsRate_Liked_Log_Sq <-  facebook_train$ImpressionsRate_Liked_Log^2
ReachRate_Log_Sq <- facebook_train$ReachRate_Log^2 
ReachRate_Liked_Log_Sq <- facebook_train$ReachRate_Liked_Log^2
EngagedRate_Log_Sq <- facebook_train$EngagedRate_Log^2  
EngagedRate_Liked_Log_Sq <- facebook_train$EngagedRate_Liked_Log^2
ConsumerRate_Log_Sq <- facebook_train$ConsumerRate_Log^2
facebook_train <- cbind(facebook_train,Impressions_in_100_Log_Sq,ImpressionsRate_Liked_Log_Sq,ReachRate_Log_Sq,ReachRate_Liked_Log_Sq,EngagedRate_Log_Sq,EngagedRate_Liked_Log_Sq,ConsumerRate_Log_Sq)
rm(Impressions_in_100_Log_Sq,ImpressionsRate_Liked_Log_Sq,ReachRate_Log_Sq,ReachRate_Liked_Log_Sq,EngagedRate_Log_Sq,EngagedRate_Liked_Log_Sq,ConsumerRate_Log_Sq)
```

```{r Model2, message=FALSE, warning=FALSE}
Model2 <- lm(consumptionRate_Log~
                 +Type+Category+Paid 
                 +Impressions_in_100_Log + Impressions_in_100_Log_Sq
                 +ImpressionsRate_Liked_Log + ImpressionsRate_Liked_Log_Sq
                 +ReachRate_Log + ReachRate_Log_Sq
                 +ReachRate_Liked_Log + ReachRate_Liked_Log_Sq
                 +EngagedRate_Log + EngagedRate_Log_Sq
                 +EngagedRate_Liked_Log + EngagedRate_Liked_Log_Sq
                 +ConsumerRate_Log + ConsumerRate_Log_Sq
                 +Interactions
                 ,data = facebook_train)

summary(Model2)
qqPlot(Model2,id.n = 10)
residualPlot(Model2)
residualPlots(Model2,id.n=10)

# influenceIndexPlot(Model2,id.n=5)
cutoff2 <- 4/((nrow(facebook_train)-length(Model2$coefficients)-2))
plot(Model2, which=4, cook.levels=cutoff2)

# Leverage points.
lev=hat(model.matrix(Model2))
plot(lev)

colnames((t(facebook_train[lev>0.2,]))) #(t(facebook_train[lev>0.2,])) 
plot( p.adjust(Model2$residuals, method = "bonferroni"))
```

```{r Model3, message=FALSE, warning=FALSE}
Model3 <- lm(consumptionRate_Log~
                 +Type+Category+Paid 
                 +Impressions_in_100_Log + Impressions_in_100_Log_Sq
                 +ImpressionsRate_Liked_Log + ImpressionsRate_Liked_Log_Sq
                 +ReachRate_Log + ReachRate_Log_Sq
                 +ReachRate_Liked_Log + ReachRate_Liked_Log_Sq
                 +EngagedRate_Log + EngagedRate_Log_Sq
                 +EngagedRate_Liked_Log + EngagedRate_Liked_Log_Sq
                 +ConsumerRate_Log + ConsumerRate_Log_Sq
                 +Interactions
                 ,data = facebook_train[-c(97,245,279,413)])
summary(Model3)
qqPlot(Model3,id.n=10)
residualPlots(Model3)

lev=hat(model.matrix(Model3))
plot(lev)

which(lev>0.2)

cutoff <- 4/((nrow(facebook_train)-1-length(Model3$coefficients)-2))
plot(Model3, which=4, cook.levels=cutoff)
```

```{r Model2_MultiCollineariry, message=FALSE, warning=FALSE}
####multicollinearity check
library(perturb)
library(MASS)
vif(Model2)
colldiag(facebook_train[,c(14:27)])
```


```{r BestSubset_Selection, message=FALSE, warning=FALSE}
###Best subset regression
step <- stepAIC(Model2, direction="both")
```


```{r Model4, message=FALSE, warning=FALSE}
Model4 <- lm(consumptionRate_Log~ 
                            Type+Category
                            +Impressions_in_100_Log_Sq+ImpressionsRate_Liked_Log
                            +ReachRate_Log+ReachRate_Liked_Log
                            +EngagedRate_Log+EngagedRate_Log_Sq+EngagedRate_Liked_Log
                            +ConsumerRate_Log_Sq
             ,data = facebook_train
             )

summary(Model4)
qqPlot(Model4)
residualPlots(Model4)
```

```{r Transformations_ValidationData, message=FALSE, warning=FALSE}
Impressions_in_100_Log <- log(facebook_Validation$Impressions_in_100)
Impressions_in_100_Log_Sq <-  Impressions_in_100_Log^2
ImpressionsRate_Liked_Log <- log(facebook_Validation$ImpressionsRate_Liked)
ReachRate_Log <- log(facebook_Validation$ReachRate)
ReachRate_Liked_Log <- log(max(facebook_Validation$ReachRate_Liked)+1-facebook_Validation$ReachRate_Liked)
EngagedRate_Log <- log(facebook_Validation$EngagedRate)
EngagedRate_Log_Sq <- EngagedRate_Log^2
EngagedRate_Liked_Log <- log(facebook_Validation$EngagedRate_Liked)
ConsumerRate_Log <- log(max(facebook_Validation$ConsumerRate)+1-facebook_Validation$ConsumerRate)
ConsumerRate_Log_Sq <- ConsumerRate_Log^2

facebook_test <- cbind(facebook_Validation,Impressions_in_100_Log_Sq,ImpressionsRate_Liked_Log,ReachRate_Log,ReachRate_Liked_Log,EngagedRate_Log,EngagedRate_Log_Sq,EngagedRate_Liked_Log,ConsumerRate_Log_Sq)

facebook_test <- facebook_test[,c(2,3,13:20)]

facebook_test <- as.data.frame(facebook_test)
 
rm(Impressions_in_100_Log,Impressions_in_100_Log_Sq,ImpressionsRate_Liked_Log,ReachRate_Log,ReachRate_Liked_Log,EngagedRate_Log,EngagedRate_Log_Sq,EngagedRate_Liked_Log,ConsumerRate_Log,ConsumerRate_Log_Sq)

consumptionRate_Log_Val  <- log(facebook_Validation$consumptionRate)
```


```{r Validating_Model, message=FALSE, warning=FALSE}
y_hat<-predict.lm (Model4,newdata= facebook_test,se.fit=TRUE)$fit
y_hat<-as.vector (y_hat)
dev<- consumptionRate_Log_Val-(y_hat)
num<-sum(dev^2)
dev1<-consumptionRate_Log_Val-mean(consumptionRate_Log_Val)
den<-sum(dev1^2)
Predicted.Rsq<-1-(num/den)
Predicted.Rsq
```



```{r Transformation_FinalData, message=FALSE, warning=FALSE}
Impressions_in_100_Log <- log(facebook_page$Impressions_in_100)
Impressions_in_100_Log_Sq <-  Impressions_in_100_Log^2
ImpressionsRate_Liked_Log <- log(facebook_page$ImpressionsRate_Liked)
ReachRate_Log <- log(facebook_page$ReachRate)
ReachRate_Liked_Log <- log(max(facebook_page$ReachRate_Liked)+1-facebook_page$ReachRate_Liked)
EngagedRate_Log <- log(facebook_page$EngagedRate)
EngagedRate_Log_Sq <- EngagedRate_Log^2
EngagedRate_Liked_Log <- log(facebook_page$EngagedRate_Liked)
ConsumerRate_Log <- log(max(facebook_page$ConsumerRate)+1-facebook_page$ConsumerRate)
ConsumerRate_Log_Sq <- ConsumerRate_Log^2

facebook_final <- cbind(facebook_page,Impressions_in_100_Log_Sq,ImpressionsRate_Liked_Log,ReachRate_Log,ReachRate_Liked_Log,EngagedRate_Log,EngagedRate_Log_Sq,EngagedRate_Liked_Log,ConsumerRate_Log_Sq)

facebook_final <- facebook_final[,c(2,3,13:20)]

facebook_final <- as.data.frame(facebook_final)
 
rm(Impressions_in_100_Log,Impressions_in_100_Log_Sq,ImpressionsRate_Liked_Log,ReachRate_Log,ReachRate_Liked_Log,EngagedRate_Log,EngagedRate_Log_Sq,EngagedRate_Liked_Log,ConsumerRate_Log,ConsumerRate_Log_Sq)

consumptionRate_Actual  <- log(facebook_page$consumptionRate)
```

```{r Predicting_FinalModel, message=FALSE, warning=FALSE}
y_hat<-predict.lm ( Model4, newdata= facebook_final, se.fit=TRUE)$fit
y_hat<-as.vector (y_hat)
dev<-consumptionRate_Actual - (y_hat)
num<-sum(dev^2)
dev1<-consumptionRate_Actual-mean(consumptionRate_Actual)
den<-sum(dev1^2)
Predicted.Rsq<-1-(num/den)
Predicted.Rsq
```


```{r Final_Model, message=FALSE, warning=FALSE}
Final_Model <- lm(consumptionRate_Actual~., data = facebook_final)
summary(Final_Model)
residualPlots(Final_Model)
qqPlot(Final_Model, main="QQ Plot of residuals: Fmodel")
```

```{r histogram_residuals, message=FALSE, warning=FALSE}
stu.resid1 <- studres(Final_Model)
hist(stu.resid1, freq=FALSE,
main="Distribution of Studentized Residuals")
xfit1<-seq(min(stu.resid1),max(stu.resid1),length=40)
yfit1<-dnorm(xfit1)
lines(xfit1, yfit1)
```

```{r Multicollinearity_FinalModel, message=FALSE, warning=FALSE}
vif(Final_Model)
colldiag(facebook_final[,c(3:10)])
```

